tokaiproject2/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView

from .views import SignupView


app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),


]

tokaiproject2/tokai/urls.py
from django.urls import path
from . import views 
from .views import FileUploadDeleteView

app_name = 'tokai'
urlpatterns = [
    path('',views.TokaiView, name='index'),
    path('tosimitu/',views.Tosimitu,name='tosimitu'),
    path('tetuya/',views.Tetuya,name='tetuya'),
    path('sibayu/',views.Sibayu,name='sibayu'),
    path('musimegane/',views.Musimegane,name='musimegane'),
    path('yumemaru/',views.Yumemaru,name='yumemaru'),
    path('ryo/',views.Ryo,name='ryo'),
    path('tokaivideo_site/',views.Video.as_view(),name='video'),
    path('mypage/',views.Mypage.as_view(),name='mypage'),
    path('upload/',views.UploadView.as_view(), name='upload'),
    path('delete/<int:pk>/',FileUploadDeleteView.as_view(), name='delete_fileupload'),

]

tokaiproject2/tokaiproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('tokai.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tokaiproject2/accounts/models.py
from django.db import models

tokaiproject2/tokai/models.py
from django.db import models
# from django.contrib.auth.models import User

# class Tokai(models.Model):
#     title = models.CharField(max_length=100)
#     text = models.TextField(default='default_text_value') 
#     thumbnail = models.ImageField(default='default_thumbnail.jpg')

class FileUpload(models.Model):
    files = models.FileField(upload_to='videos/')
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.files)

    class Meta:
        db_table = 'tokai_fileupload'

tokaiproject2/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)

tokaiproject2/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView 
from .forms import SignupForm


class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('tokai:index')


    

tokaiproject2/tokai/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from .models import FileUpload
from .form import UploadForm
from django.views.generic import CreateView,ListView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import View
import logging
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from .models import FileUpload


from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from .models import FileUpload

class FileUploadDeleteView(LoginRequiredMixin, DeleteView):
    model = FileUpload
    success_url = reverse_lazy('tokai:mypage')
    
    def get_queryset(self):
        # ログインユーザーが所有するファイルのみを対象にする
        return super().get_queryset().filter(user=self.request.user)

    def get_success_url(self):
        return self.success_url

 

class UploadView(LoginRequiredMixin,CreateView):
    template_name = 'tokai/create.html'
    model = FileUpload
    fields = ('files',)
    success_url = reverse_lazy('tokai:mypage')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

def TokaiView (request):
    return render(request, 'tokai/index.html',)

def Tosimitu(request):
    return render(request,'tokai/Tosimitu.html')

def Tetuya(request):
    return render(request,'tokai/Tetuya.html')

def Sibayu(request):
    return render(request,'tokai/Sibayu.html')

def Musimegane(request):
    return render(request,'tokai/Musimegane.html')

def Yumemaru(request):
    return render(request,'tokai/Yumemaru.html')

def Ryo(request):
    return render(request,'tokai/Ryo.html')


class Video(ListView):
    template_name='tokai/video_site.html'
    model = FileUpload
    context_object_name = 'videos' 

    def get_queryset(self):
        return FileUpload.objects.all()
        
    
class Mypage(LoginRequiredMixin,ListView):
    template_name='tokai/mypage.html'
    model = FileUpload
    context_object_name = 'file_list' 
    
    def get(self, request, *args, **kwargs):
        logger = logging.getLogger(__name__)
        logger.info("User: %s", request.user)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = FileUpload.objects.filter(user=self.request.user)
        logger = logging.getLogger(__name__)
        logger.info("Queryset: %s", queryset)
        return queryset

tokaiproject2/accounts/templates/accounts/signup.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
        <link rel="stylesheet" href="{%static 'tokai/css/signup.css'%}">

    <title>Tokaionair_roguinpage</title>
    </head>
    <body>
    {% block content %}
        <div class="infomation">
            <p class="logo">
                <img src="{% static 'tokai/img/onerbard.PNG' %}">
            </p>
            <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
                {% csrf_token %}
                {% for error in form.errors.values %}
                    {{ error }}
                {% endfor %}
                <ul>
                    <label class="user_id">
                        ユーザー名
                    </label>
                    <input class="form-control" name="username">
                    <label class="password">
                        パスワード
                    </label>
                        <input type="password" class="form-control" name="password1" placeholder="パスワード">
                    
                    <label class="password2">
                        パスワード確認用
                    </label>
                    <input type="password" class="form-control" name="password2" placeholder="パスワード確認用">
                    <small class="text1">パスワードは８文字以上で設定してください</small>
                    {% if form.errors %}
                    <span class="text2">利用できないユーザーIDやパスワードの可能性があります。再度ご確認ください。
                    </span>
                    {% endif %}
                    <li>
                       <button type="submit" >新規登録</button>
                    </li>
                </ul>
            </form>
        </div>
        {% endblock %}
    </body>
</html>

tokaiproject2/tokai/templates/tokai/Musimegane.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/musimegane.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <title>Tokaionair_Musimegane</title>
    </head>
    <main>
        <section class="first">
            <img src="{% static 'tokai/img/musimegane_2.JPG'%}" alt="musimegane">
            <div class="content">
            <div class="name">
            <h1>MUSIMEGANE</h1>
            </div>
            <div class="text">
                <p>1992/9/29 A型</p>

<p>「東海オンエアの控え室編集長」</p>

<p>動画内の概要欄をまとめた著書「東海オンエアの動画が6.4倍楽しくなる本」を2018年に出版、その後続編も定期的に発売されるなど人気シリーズになっている。</p>
<p>ゆめまるとともにメインパーソナリティを務める「東海オンエアラジオ」、「東海オンエア虫眼鏡・島﨑信長 声YouラジオZ」、「虫眼鏡の放送部」、音声アプリ「REC.」など
精力的にラジオ活動も行っている。</p>
<p>好きなアイドルはでんぱ組.incさん。</p>
            </div>
           </div>
           </section>
            <section class="link">
            <h1>LINKS</h1>
            <ul>
       <li> <a href="https://www.youtube.com/channel/UCbSIiNFWbJCW8ERBbkNMfwQ" >虫眼鏡の放送部 YouTube</a></li>

        <li><a href="https://twitter.com/TO_ZAWAKUN">虫眼鏡【東海オンエア】 Twitter</a></li>
        
        <li><a href="https://www.instagram.com/to_mushimegane/">虫眼鏡【東海オンエア】 Instagram</a></li>
      </ul> 
     </section>
    </main>

tokaiproject2/tokai/templates/tokai/Ryo.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/ryo.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <title>Tokaionair_Ryo</title>
    </head>
    <main>
        <section class="first">
             <img src="{% static 'tokai/img/ryou_2.JPG' %}" alt="ryo">
            
            <div class="content">
            <div class="name">
              <h1>RYO</h1>
            </div>
            <div class="text">
                <p>1993/06/11 O型</p>

<p>ディレクション大臣」</p>

<p>有名海外選手とのコラボレーションや、チャンピオンズリーグ決勝を現地で
観戦するほど大の海外サッカー好き。</p>
 <p>個人では2020年7月に地元岡崎市にてカフェ「R COFFEE STAND」
をオープンした。</p> 
<p>自身の個人チャンネルである「ブラーボりょうのボンサバドゥ! チャンネル」
も運営している。</p>
<p>東海オンエアにとって最も重要といっても過言ではない「動画の制作進行・
スケジュール管理」を行うなどまさに縁の下の力持ち。</p>
<p>好きなサッカークラブはチェルシーFC。</p>
            </div>
            </div>
          </section>
            <section class="link">
            <h1>LINK</h1>
            <ul>
           <li> <a href="https://www.youtube.com/channel/UCigMkMDZjvLhXAQ67wKQIbA">ブラーボりょうのボンサバドゥ!チャンネル YouTube</a></li>
<li><a href="https://twitter.com/TO_RYOO">りょう【東海オンエア】 Twitter </a></li>
<li><a href="https://www.instagram.com/to_ryoo/">東海オンエアのりょう Instagram</a></li>
<li><a href="https://www.rcoffeestand.com/">R COFFEE STAND</a></li>
      </ul>
      </section>
    </main>

tokaiproject2/tokai/templates/tokai/Sibayu.html
{%load static%}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/sibayu.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <title>Tokaionair_Sibayu</title>
    </head>
    <main>
      <section class="first">
       <img src="{% static 'tokai/img/sibayu_2.JPG' %}" alt="sibayu">
        <div class="content">
          <div class="name">
            <h1>SIBAYU</h1>
          </div>
        <div class="text">
         <p> 1993/12/30 ？型</p>

<p>「ストーリーズ大臣」</p>

<p>東海オンエア結成当初からグループのエースとしてチャンネルを盛り上げてきたしばゆー。</p>
<p>独特なセンスと表現力を持ち合わせており、東海オンエアの主砲と呼ばれている。</p>
<p>グループ内で結成された目立ちたがり屋ユニットの「リサイタルズ」では作詞も担当。</p>
<p>YouTubeチャンネル「ニンマリシティへようこそ」のマッドロイ機長とは何かしらの関係があるとかないとか。</p>
<p>好きなアーティストは三浦大知さん。</p>
        </div>
      </div>
    </section>
      <section class="link">
        <h1>LINKS</h1>
        <ul>
          <li><a href="https://twitter.com/TOKAI_ONAIR">しばゆー【東海オンエア】 Twitter</a> </li>
            <li><a href="https://www.instagram.com/to___shibayu/">しばゆー Instagram</a></li>
        </ul>
      </section>
    </main>

tokaiproject2/tokai/templates/tokai/Tetuya.html
{%load static%}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/tetuya.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <title>Tokaionair_Tetuya</title>
    </head>
    <main>
    <section class="first">
    <img src="{% static 'tokai/img/tetuya_2.JPG' %}" alt="tetuya">
    <div class="content">
    <div class="name">
    <h1>TETUYA</h1>
</div>
<div class="text">
    <p>10/30（年齢非公開） A型</p>

        <p>「東海オンエアのリーダー」</p>
        
        <P>個性が強いグループメンバーの中でも天才的な発想と圧倒的なカリス
        マ性を誇り、リーダーとしてグループを牽引。</P>
        <p>2020年12月には自身初のエッセイ「天才の根源」を発表した。</p>
        <p>てつやの個人チャンネルである「べりたんで検索お願いします」 
        ではゲーム実況や商品紹介を行っている。</p></p>
        <p>好きなものにとことん本気で向き合うタイプ。
       <p> 朝は弱い。</p>
      <p>  趣味はスプラトゥーン。</p>
       </div>
      </div>
    </section>
       <section class="link">
        <h1>LINK</h1>

            <ul>
  <li>  <a href="https://youtube.com/@NoTetsuyaNoLife"> ベリたんで検索お願いします YouTube</a></li>
    
<li><a href="https://twitter.com/TO_TETSUYA">てつや【東海オンエア】Twitter</a></li>

<li><a href="https://www.instagram.com/to_tetsuya/">てつや【東海オンエア】Instagram</a></li>
            </ul>
     
</section>
    </main>

tokaiproject2/tokai/templates/tokai/Tosimitu.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/tosimitu.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <title>Tokaionair_Tosimitu</title>
    </head>
    <main>
      <section class="first">
    
        <img src="{% static 'tokai/img/tosimitu_2.JPG' %}" alt="tosimitu">
        
        <div class="content">
        <div class="name">
          <h1>TOSIMITU</h1>
          </div>
          <div class="text">
          <p>1993/07/17 O型</p>

<p>「グッズ・イベント大臣」</p>

<p>2019年6月にソロアーティスト“TOSHIMITSU”としてミニアルバム『THE BEST』『THE BEST2』をリリース、 2020年2月には自身初のワンマンライブを開催するなどアーティストとしても活動し、LIVEでは常に全力のパフォーマンスでファンを魅了し続けている。 自身の個人チャンネルである「としみつ東海オンエアの」でもMVやカバーソングを公開するなど音楽を中心に投稿。</p>
<p>終わらない青春、漢としみつなど異名多数。</p>
<p>東海オンエアのグッズ、イベント担当としていつもファンを想って次の一手を考えている。</p>
<p>好きな食べものは五平餅。</p>
        </div>
      </div>
    </section>
      <section class="link">
        <h1>LINKS</h1>
        <ul>
          <li><a href="https://www.youtube.com/channel/UCDFxQgB9Dc_MzxiEKjozWwg">としみつ東海オンエアのYouTube</a></li>
            
            <li><a href="https://twitter.com/TO_TOSHIMITSU">としみつ【東海オンエア】Twitter</a></li>
            
           <li><a href="https://www.instagram.com/toshimitsu_tokaionair"> 東海オンエアのとしみつInstagram</a></li>
            
            <li><a href="https://tiktok.com/@to_toshimitsu">東海オンエアのとしみつTikTok </a></li>
           
        </ul>
      </section>
    </main>

tokaiproject2/tokai/templates/tokai/Yumemaru.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/yumemaru.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <title>Tokaionair_Yumemaru</title>
    </head>
    <main>
    <section class="first">
        <img src="{% static 'tokai/img/yumemaru_2.JPG'%}" alt="yumemaru">
        <div class="content">
        <div class="name">
        <h2>YUMEMARU</h2>
        </div>
        
        <div class="text">
            <p>1994/01/23 B型</p>

<p>「メンバーシップ大臣」</p>

<p>東海オンエアの発起人的存在。</p>
<p>グループ内でも随一のお酒好きとして知られており、個人でも Webマガジンにてお酒の連載仕事を行っている。</p>
<p>レギュラー番組「東海オンエアラジオ」では虫眼鏡とともにメインパーソナリティを務め、トーク力に磨きがかかっている。</p>
<p>2020年8月にはアパレルブランド「Bark at the Moon」 を立ち上げた。</p>
<p>自身の個人チャンネルである「ゆめまる美術館」では「Bark at the Moon」の新作情報を中心に投稿中。</p>
<p>旅ロケ風の演技が得意。</p>
 </div>
</div>
</section>
<section class="link">
 <h1>LINKS</h1>
 <P>
    <ul>
     <li><a href="https://www.youtube.com/channel/UCevQsKO8q1XQcEA1BoBO2gA">ゆめまる美術館 YouTube</a></li>      
     <li> <a href="https://twitter.com/TO_yumemarucas">ゆめまる【東海オンエア】Twitter</a></li>
    <li> <a href="https://www.instagram.com/yumemaru_original/">ゆめまる（本人）Instagram</a></li>
    <li> <a href="https://bark-at-the-moon.shop/">Bark at the Moon</a></li>
    </ul>
 </P>
</section>
    </main>

tokaiproject2/tokai/templates/tokai/index.html
{%load static%}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/style.css'%}">
    
    <title>Tokaionair</title>
    </head>
    <body>
        
    <header>  
       <nav>
        <div class="top">
                <div><a href="#top">
                <img class="onerbard" src="{% static 'tokai/img/onerbard.PNG'%}" alt="onerbard"></a>
                </div>
                
                    <input type="checkbox" class="menu-btn" id="menu-btn">
                
                    <label for="menu-btn" class="menu-icon"><span class="navicon"></span></label>
               
            
            
                <ul class="menu">
            
                <li class="nav_youtube"><a href="#youtube">YouTube</a></li>
                <li class="nav_profile"><a href="#Profile">Profile</a></li>
                <li class="nav_store"><a href="#Store">Store</a></li>
                <li><a href="{% url 'tokai:video' %}">video site</a></li>
                <!-- {% if request.user.is_authenticated %}
                    <form action="{% url 'accounts:logout' %}" method="post" name="logout">{% csrf_token %}
                        <li class="nav_mypage">
                            <a href="javascript:logout.submit()">logout</a>
                        </li>
                    </form>
                {% else %}
                    <li class="nav_mypage"><a href="{% url 'accounts:login' %}">video site</a></li>
                {% endif %} -->
                </ul>
        </div> 
        </nav>
            
            <h1 class="tokai">
            
                <img src="{% static 'tokai/img/1_tokai.jpg' %}" alt="header">
            </h1> 
            
    </header>

        <main>
        <section>
            <div class="anniversary">
            <a href="https://tokaionair.jp/pages/10th-anniversary"><img src="{% static 'tokai/img/anniversary.jpg' %}" alt="anniversary"></a>
        </div>
    </section>

        <section>
        
            <div class="Profile">
            <h1 id="Profile">Profile</h1>
            <div class="Profile_content">
            <ul class="first_img">
            <li><a href="{% url 'tokai:tosimitu' %}"><img src="{% static 'tokai/img/tosimitu_1.JPG' %}" alt="tosimitu"></a></li>
            <li><a href="{% url 'tokai:tetuya' %}"><img src="{% static 'tokai/img/tetuya_1.JPG' %}" alt="tetuya"></a></li>
            <li><a href="{% url 'tokai:sibayu' %}"><img src="{% static 'tokai/img/sibayu_1.JPG' %}" alt="sibayu"></a></li>
           </ul>
           <ul class="second_img">
            <li><a href="{% url 'tokai:musimegane' %}"><img src="{% static 'tokai/img/musimegane_1.JPG' %}" alt="musimegane"></a></li>
            <li><a href="{% url 'tokai:yumemaru' %}"><img src="{% static 'tokai/img/yumemaru_1.JPG' %}" alt="yumemaru"></a></li>
            <li><a href="{% url 'tokai:ryo' %}"><img src="{% static 'tokai/img/ryou_1.JPG' %}" alt="ryo"></a></li>
       </ul>
    </div>
     </div>
    </section>
    <section>
        <div class="youtube">
           
            <div id="youtube">
        <h1>人気動画</h1>
        <ul>
        <li><iframe  src="https://www.youtube.com/embed/ygiQOJoY_9A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></li>
       <li><iframe  src="https://www.youtube.com/embed/iX35yxAxMp0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></li>
        <li><iframe  src="https://www.youtube.com/embed/xkQOFe1Fjfw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></li>
        <li><iframe  src="https://www.youtube.com/embed/ABkpsORJwxI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></li>
        <Li><iframe  src="https://www.youtube.com/embed/Tz2dbJCDt_I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></Li>
 </div>

</div>
</section>
    <section class="osusume">
        <div class="cont">
    <p><iframe src="https://www.youtube.com/embed/XqlK3lzmcLA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></p>
   </div>
   
    <img class="nijyou" src="{% static 'tokai/img/nijyoukun.PNG' %}" alt="nijyoukun">
 
 </section>
    <section>
        <div class="store">
        <h1 id="Store">Official store </h1>
        <div class="store_img">
        <a href="https://tokaionair.jp/"><img src="{% static 'tokai/img/official store.png' %}" alt="official store"></a>
        </div>
    </section>
        </div>
       
    </div>
    </body>
        </main>
        <footer>
            TOKAIONAIR
        </footer>
</body>
</html>


       

tokaiproject2/tokai/templates/tokai/mypage.html
{%load static%}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/my.css'%}">
    <title>Tokaionair_video_share_mypage</title>
</head>

<body>
    <div class="menu">
        <div class="menu_botan">
            <a  href="{% url 'tokai:video' %}">Top</a>
            <form action="{% url 'accounts:logout' %}" method="post" name="logout">
            {% csrf_token %} 
            <a href="javascript:logout.submit()">logout</a>
        </div>
    </div>

    <div class="account">
        <p>アカウント名</p>
        <p class="my_name">{{ user.get_username }}</p>
    </div>
    
    <p class="video">動画</p>

    <div class="video_list">
        
        {% if user.is_authenticated %}
            {% if file_list %}
                <ul class="V">
                {% for file in file_list %}

                <li>
                    <video width="220" height="300" controls>
                        <source src="{{ file.files.url }}" type="video/mp4">
                        <form method="post" action="{% url 'tokai:delete_fileupload' file.id %}">
                            {% csrf_token %}
                            <button type="submit">削除</button>
                        </form>
                    </video>
                        <form method="post" action="{% url 'tokai:delete_fileupload' file.id %}">
                            {% csrf_token %}
                            <button type="submit">削除</button>
                        </form>
                </li>
                {% endfor %}        
            
                </ul>
            {% else %}
            <p>No files uploaded yet.</p>
            {% endif %}
        {% else %}
            <p>Please log in to view your files.</p>
        {% endif %}

    </div>
    <div class="create_botan">
        <a class="new" href="{% url 'tokai:upload' %}">投稿</a>
    </div>
    <script>
        function confirmDelete(fileId) {
            if (confirm("この動画を削除してもよろしいですか？")) {
                document.getElementById("delete-form-" + fileId).submit();
            }
        }
    </script>
</body>

tokaiproject2/tokai/templates/tokai/video_site.html
{%load static%}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/video_site.css'%}">
    <title>Tokaionair_video_share</title>
  </head>
  <body>    
    <header>
       <nav>
        <div class="top">
          <div class="bar">
            <a href="#top">
              <img class="onerbard" src="{% static 'tokai/img/onerbard.PNG'%}" alt="onerbard">
            </a>
            <input type="checkbox" class="menu-btn" id="menu-btn">
            <label for="menu-btn" class="menu-icon"><span class="navicon"></span></label>
            <ul class="menu">    
              <li><a href="{% url 'tokai:index' %}">Top site</a></li>
              {% if request.user.is_authenticated %}
              <form action="{% url 'accounts:logout' %}" method="post" name="logout">{% csrf_token %}
                <li><a href="{% url 'tokai:mypage' %}">mypage</a></li>
              </form>
            </div>
            {% else %}
            <li class="nav_mypage"><a href="{% url 'accounts:login' %}">mypage</a></li>
            {% endif %}
          </ul>
        </div>
       </nav>
    </header>
       <div>

        {% if videos %}
          <ul class="V">
            {% for file in videos %}
              <li class="V">
                <video width="200" height="285" controls>
                  <source src="{{ file.files.url }}" type="video/mp4">
                </video>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>No files uploaded yet.</p>
        {% endif %}
       </div>
  </body>
</html>

       
               