tokaiproject/tokai/urls.py
from django.urls import path
from . import views 

app_name = 'tokai'
urlpatterns = [
    path('',views.TokaiView, name='index'),
    path('tosimitu/',views.Tosimitu,name='tosimitu'),
    path('tetuya/',views.Tetuya,name='tetuya'),
    path('sibayu/',views.Sibayu,name='sibayu'),
    path('musimegane/',views.Musimegane,name='musimegane'),
    path('yumemaru/',views.Yumemaru,name='yumemaru'),
    path('ryo/',views.Ryo,name='ryo'),
    path('tokaivideo_site/',views.Video.as_view(),name='video'),
    path('mypage/',views.Mypage.as_view(),name='mypage'),

    path('upload/',views.UploadView.as_view(), name='upload'),
]

tokaiproject/tokai/models.py
from django.db import models
from django.contrib.auth.models import User

# class Tokai(models.Model):
#     title = models.CharField(max_length=100)
#     text = models.TextField(default='default_text_value') 
#     thumbnail = models.ImageField(default='default_thumbnail.jpg')

# class FileUpload(models.Model):
#     files = models.FileField(upload_to='videos/')
#     user = models.ForeignKey(User, on_delete=models.CASCADE)

#     def __str__(self):
#         return str(self.files)
from django.db import models
from django.contrib.auth.models import User

class FileUpload(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    files = models.FileField(upload_to='uploads/')

    def __str__(self):
        return f"{self.user.username} - {self.files.name}"

tokaiproject/tokai/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from .models import FileUpload
from .form import UploadForm
from django.views.generic import CreateView,ListView
# from .models import Tokai
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import View
import logging
# from django.views import View




class UploadView(LoginRequiredMixin,CreateView):
    template_name = 'tokai/create.html'
    model = FileUpload
    fields = ('files',)
    success_url = reverse_lazy('tokai:mypage')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    # def some_method(self):
    #     # user_id 列にアクセスする例
    #     upload_instance = FileUpload.objects.get(pk=1)  # 適切な条件を指定して取得
    #     user_id_value = upload_instance.user_id
    


def TokaiView (request):
    return render(request, 'tokai/index.html',)

def Tosimitu(request):
    return render(request,'tokai/Tosimitu.html')

def Tetuya(request):
    return render(request,'tokai/Tetuya.html')

def Sibayu(request):
    return render(request,'tokai/Sibayu.html')

def Musimegane(request):
    return render(request,'tokai/Musimegane.html')

def Yumemaru(request):
    return render(request,'tokai/Yumemaru.html')

def Ryo(request):
    return render(request,'tokai/Ryo.html')


class Video(ListView):
    template_name='tokai/video_site.html'
    model = FileUpload
    context_object_name = 'videos'  # テンプレート内で使用する変数名

    def get_queryset(self):
        return FileUpload.objects.all()

class Mypage(LoginRequiredMixin,ListView):
    template_name='tokai/mypage.html'
    model = FileUpload
    context_object_name = 'file_list'

    

def get(self, request, *args, **kwargs):
        logger = logging.getLogger(__name__)
        logger.info("User: %s", request.user)
        return super().get(request, *args, **kwargs)
def get_queryset(self):
        queryset = FileUpload.objects.filter(user=self.request.user)
        logger = logging.getLogger(__name__)
        logger.info("Queryset: %s", queryset)
        return queryset

tokaiproject/tokai/templates/tokai/create.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/create.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">

<body>
    


{% block title %}新規投稿{% endblock %} 

{% block content %}
<!-- <form method="POST" enctype="multipart/form-data"> -->
    <form method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="投稿する">
</form>
    {% endblock content %}

</body>

tokaiproject/tokai/templates/tokai/mypage.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/mypage.css'%}">
    <title>Tokaionair_video_share_mypage</title>
</head>
<body>
    <div class="menu">
        <div class="menu_botan">
            <a  href="{% url 'tokai:video' %}">Top</a>
            <form action="{% url 'accounts:logout' %}" method="post" name="logout">
            {% csrf_token %}
            <a href="javascript:logout.submit()">logout</a>
        </div>
    </div>
    <div class="account">
        <p>アカウント名</p>
        <p class="my_name">{{ user.get_username }}</p>
    </div>
    <p class="video">動画</p>
    <div class="video_list">
        {% if user.is_authenticated %}
            {% if file_list %}
            <ul>
                {% for file in file_list %}
                <li>
                    <video width="320" height="600" controls>
                    <source src="{{ file.files.url }}" type="video/mp4">
                    </video>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No files uploaded yet.</p>
            {% endif %}
        {% else %}
            <p>Please log in to view your files.</p>
        {% endif %}
    </div>
    <div class="create_botan">
        <a class="new" href="{% url 'tokai:upload' %}">投稿</a>
    </div>
</body>

tokaiproject/tokai/templates/tokai/video_site.html
{%load static%}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{%static 'tokai/css/reset.css'%}">
    <link rel="stylesheet" href="{%static 'tokai/css/video_site.css'%}">
    <title>Tokaionair_video_share</title>
  </head>
  <body>
    <header>
       <nav>
        <div class="top">
          <div>
            <a href="#top">
              <img class="onerbard" src="{% static 'tokai/img/onerbard.PNG'%}" alt="onerbard">
            </a>
          </div>
          <input type="checkbox" class="menu-btn" id="menu-btn">
          <label for="menu-btn" class="menu-icon"><span class="navicon"></span></label>
          <ul class="menu">
            <li><a href="{% url 'tokai:index' %}">Top site</a></li>
            {% if request.user.is_authenticated %}
            <form action="{% url 'accounts:logout' %}" method="post" name="logout">{% csrf_token %}
                  <li><a href="{% url 'tokai:mypage' %}">mypage</a></li>
            </form>
            {% else %}
            <li class="nav_mypage"><a href="{% url 'accounts:login' %}">mypage</a></li>
            {% endif %}
          </ul>
        </div>
       </nav>
    </header>
       <div class="V">
        {% if videos %}
          <ul>
            {% for file in videos %}
              <li>
                <video width="240" height="285" controls>
                  <source src="{{ file.files.url }}" type="video/mp4">
                </video>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>No files uploaded yet.</p>
        {% endif %}
       </div>
  </body>
</html>